debug:
  update_interval: 10s

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
  
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: uptime
    name: Uptime Sensor
    update_interval: 10s

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"

- platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 10
    filters:
       - median:
          window_size: 3
          send_every: 1
          send_first_at: 1

psram:
  mode: octal
  speed: 80MHz
