debug:
  update_interval: 5s

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
  
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: uptime
    name: Uptime Sensor
    update_interval: 5s

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"

psram:
  mode: octal
  speed: 80MHz
